services:

  # database service
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
    restart: always


# application service
  fastapi-app:
    container_name: users_notification
    build: .
    command: python main.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - mongo
    restart: always
    networks:
      - custom
    env_file:
      - .env

networks:
  custom:
    driver: bridge
